name: 'Push Cloudflare'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 10 15 * *' # At 10:00 on day-of-month 15  

jobs:
  push-cloudflare:
    name: 'Push Cloudflare'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete
        run: python3 api_cloudflare_delete.py
        env:
          CLOUDFLARE_TEAM_ID: ${{ secrets.cloudflare_team_id }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.cloudflare_auth_email }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.cloudflare_auth_key }}    
      - name: Create
        run: python3 api_cloudflare_create.py
        env:
          CLOUDFLARE_TEAM_ID: ${{ secrets.cloudflare_team_id }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.cloudflare_auth_email }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.cloudflare_auth_key }}              
