name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 10 15 * *' # At 10:00 on day-of-month 15  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Delete previous policy
        run: |
          curl --request GET --url https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_TEAM_ID/gateway/rules \
            --header 'Content-Type: application/json' --header 'X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL' --header 'X-Auth-Key: $CLOUDFLARE_AUTH_KEY' | \ 
            jq ".result[]" | jq 'select(.name=="DNS Blocklist").id' | { read uuid; \ 
            curl --request DELETE --url https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_TEAM_ID/gateway/rules/$uuid \ 
            --header 'Content-Type: application/json' --header 'X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL' --header 'X-Auth-Key: $CLOUDFLARE_AUTH_KEY'}
        env:
          CLOUDFLARE_TEAM_ID: ${{ secrets.cloudflare_team_id }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.cloudflare_auth_email }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.cloudflare_auth_key }}
      - name: Delete all the previous lists
        run: |
          curl --request GET --url https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_TEAM_ID/gateway/lists \
            --header 'Content-Type: application/json' --header 'X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL' --header 'X-Auth-Key: $CLOUDFLARE_AUTH_KEY' | \
            for i in $(jq ".result[].id") ;do curl --request DELETE --url https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_TEAM_ID/gateway/lists/$i \ 
            --header 'Content-Type: application/json' --header 'X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL' --header 'X-Auth-Key: $CLOUDFLARE_AUTH_KEY' ; done
        env:
          CLOUDFLARE_TEAM_ID: ${{ secrets.cloudflare_team_id }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.cloudflare_auth_email }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.cloudflare_auth_key }}            
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Destroy Blocklists
        run: terraform destroy -target cloudflare_teams_list.blocklist -auto-approve
      - name: Terraform Destroy Policy
        run: terraform destroy -target cloudflare_teams_rule.blocklist_dns_policy -auto-approve        
      - name: Terraform Apply
        run: terraform apply -auto-approve
