name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 10 15 * *' # At 10:00 on day-of-month 15  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Delete previous lists and policy
        continue-on-error: true
        run: bash api_cloudflare_delete.sh
        env:
          CLOUDFLARE_TEAM_ID: ${{ secrets.cloudflare_team_id }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.cloudflare_auth_email }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.cloudflare_auth_key }}          
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan      
      - name: Terraform Apply
        run: terraform apply -auto-approve
